#!/bin/sh /etc/rc.common
# Place this in: package/my_package/my_api/files/myapi.init

START=99
STOP=15

USE_PROCD=1
PROG=/usr/bin/myapi

start_service() {
    procd_open_instance
    procd_set_param command "$PROG"
    procd_set_param respawn ${respawn_threshold:-3600} ${respawn_timeout:-5} ${respawn_retry:-5}
    procd_set_param stdout 1
    procd_set_param stderr 1
    procd_close_instance
}

stop_service() {
    killall myapi 2>/dev/null
}

reload_service() {
    stop
    start
}
